export const REQUEST_SPOTS_PENDING ='REQUEST_SPOTS_PENDING'
export const REQUEST_SPOTS_SUCCESS ='REQUEST_SPOTS_SUCCESS'
export const REQUEST_SPOTS_FAILED ='REQUEST_SPOTS_FAILED'

export const GET_ADDRESS = 'GET_ADDRESS'
export const GET_LNG = "GET_LNG"
export const GET_LAT = "GET_LAT"