export const REQUEST_SPOTS_PENDING ='REQUEST_SPOTS_PENDING'
export const REQUEST_SPOTS_SUCCESS ='REQUEST_SPOTS_SUCCESS'
export const REQUEST_SPOTS_FAILED ='REQUEST_SPOTS_FAILED'
export const CHANGE_ACTIVE_SPOT = "CHANGE_ACTIVE_SPOT"

export const GET_ADDRESS = 'GET_ADDRESS'
export const GET_LNG = "GET_LNG"
export const GET_LAT = "GET_LAT"

export const CHANGE_ROUTE = 'CHANGE_ROUTE'  